// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvTjh-wHQ692CduXxAnST4D3GZQ7sNvl8',
    appId: '1:16348403087:android:1339cd926438eff43e27fa',
    messagingSenderId: '16348403087',
    projectId: 'tourvn-mobile-2026',
    storageBucket: 'tourvn-mobile-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCh8ASr_Ok5Ff2NHd_SljHhH5RvB2XPho',
    appId: '1:16348403087:ios:0b3dbdf595f963163e27fa',
    messagingSenderId: '16348403087',
    projectId: 'tourvn-mobile-2026',
    storageBucket: 'tourvn-mobile-2026.firebasestorage.app',
    iosBundleId: 'com.tourvn.tourVn',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvTjh-wHQ692CduXxAnST4D3GZQ7sNvl8',
    appId: '1:16348403087:web:1339cd926438eff43e27fa',
    messagingSenderId: '16348403087',
    projectId: 'tourvn-mobile-2026',
    authDomain: 'tourvn-mobile-2026.firebaseapp.com',
    storageBucket: 'tourvn-mobile-2026.firebasestorage.app',
  );
}
