import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../../auth/presentation/providers/auth_provider.dart';
import '../../data/repositories/saved_repository.dart';
import '../../domain/entities/saved_item.dart';

/// Repository provider.
final savedRepositoryProvider = Provider<SavedRepository>((ref) {
  return SavedRepository();
});

/// Stream of all saved items for the current user.
final savedItemsProvider = StreamProvider<List<SavedItem>>((ref) {
  final user = ref.watch(currentUserProvider);
  if (user == null) return Stream.value([]);

  final repo = ref.watch(savedRepositoryProvider);
  return repo.watchSavedItems(user.uid);
});

/// Check if a specific item is saved — family provider keyed by itemId.
final isItemSavedProvider =
    StreamProvider.family<bool, String>((ref, itemId) {
  final user = ref.watch(currentUserProvider);
  if (user == null) return Stream.value(false);

  final repo = ref.watch(savedRepositoryProvider);
  return repo.watchIsItemSaved(user.uid, itemId);
});

/// All saved location IDs (for AI planner integration).
final savedLocationIdsProvider = FutureProvider<List<String>>((ref) async {
  final user = ref.watch(currentUserProvider);
  if (user == null) return [];

  final repo = ref.watch(savedRepositoryProvider);
  return repo.getSavedLocationIds(user.uid);
});

/// Actions notifier for save/unsave operations (Riverpod v3 Notifier API).
class SavedActionsNotifier extends Notifier<void> {
  @override
  void build() {}

  /// Toggle save state for an item.
  Future<void> toggleSave({
    required String itemId,
    required String itemType,
    required String title,
    String? imageUrl,
    String? destinationId,
    String? destinationName,
  }) async {
    final user = ref.read(currentUserProvider);
    if (user == null) return;

    final repo = ref.read(savedRepositoryProvider);

    try {
      // Check current state
      final snapshot = await repo
          .watchIsItemSaved(user.uid, itemId)
          .first;

      if (snapshot) {
        // Currently saved → unsave
        await repo.unsaveItem(user.uid, itemId);
      } else {
        // Not saved → save
        final item = SavedItem(
          id: '', // Auto-generated by Firestore
          itemId: itemId,
          itemType: itemType,
          title: title,
          imageUrl: imageUrl,
          destinationId: destinationId,
          destinationName: destinationName,
          savedAt: DateTime.now(),
        );
        await repo.saveItem(user.uid, item);
      }
    } catch (e) {
      // Re-throw so UI can handle
      throw Exception('Lưu thất bại: $e');
    }
  }

  /// Delete a saved item by document ID.
  Future<void> deleteById(String docId) async {
    final user = ref.read(currentUserProvider);
    if (user == null) return;

    final repo = ref.read(savedRepositoryProvider);
    await repo.deleteById(user.uid, docId);
  }
}

/// Provider for saved actions.
final savedActionsProvider =
    NotifierProvider<SavedActionsNotifier, void>(
  SavedActionsNotifier.new,
);
